[package]
name = "dvs-fast-corners"
version = "0.1.0"
edition = "2021"

[dependencies]
aedat = "1.3.2"
clap = {version ="4.2.1", features = ["derive"]}
ndarray = "0.15.6"
image = "0.24.6"
show-image = {version = "0.13.1", features = ["image"]}

[profile.release]
lto = true
opt-level = 3
